import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./Component/Navbar";
import Footer from "./Component/Footer";

const outfit = Outfit({
  subsets: ["latin"],
  weight:["400","500","600","700"]
});



export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider >
 <html lang="en">
      <body
        className={outfit.className}
      >
          <Navbar />
              {children}
          <Footer />
      </body>
    </html>
    </ClerkProvider>
   
  );
}
